Repository hibobio/transaction-outbox, pull requests merged in 2025-05, with the labels that each got.

#2 gradle project settings
  .gitignore
  build.gradle.kts
  gradle.properties
  gradle/gradle-daemon-jvm.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle.kts
  transactionoutbox-acceptance/build.gradle.kts
  transactionoutbox-core/build.gradle.kts
  transactionoutbox-guice/build.gradle.kts
  transactionoutbox-jackson/build.gradle.kts
  transactionoutbox-jooq/build.gradle.kts
  transactionoutbox-quarkus/build.gradle.kts
  transactionoutbox-spring/build.gradle.kts
  transactionoutbox-testing/build.gradle.kts
  transactionoutbox-virtthreads/build.gradle.kts
Labels: Review effort 3/5

#4 gradle settings * applied platform bom dependencies * daemon jvm 17 * quarkus native image for gradle
  build.gradle.kts
  gradle.properties
  gradle/gradle-daemon-jvm.properties
  gradle/libs.versions.toml
  transactionoutbox-acceptance/build.gradle.kts
  transactionoutbox-core/build.gradle.kts
  transactionoutbox-guice/build.gradle.kts
  transactionoutbox-jackson/build.gradle.kts
  transactionoutbox-jooq/build.gradle.kts
  transactionoutbox-quarkus/build.gradle.kts
  transactionoutbox-quarkus/src/test/resources/application.properties
  transactionoutbox-spring/build.gradle.kts
  transactionoutbox-testing/build.gradle.kts
  transactionoutbox-virtthreads/build.gradle.kts
Labels: Review effort 3/5

#3 hibobio github workflows
  .github/workflows/pull_request.yaml
  .github/workflows/release_workflow.yaml
  .github/workflows_upstream/cd_build.yml
  .github/workflows_upstream/pull_request.yml
  .github/workflows_upstream/release.yml
  build.gradle.kts
Labels: Review effort 2/5

#1 Support for ordered batching
  pom.xml
  settings.xml
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/DefaultDialect.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/DefaultPersistor.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/Dialect.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/Invocation.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/Persistor.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/StubPersistor.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/TransactionOutbox.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/TransactionOutboxImpl.java
  transactionoutbox-core/src/main/java/com/gruelbox/transactionoutbox/spi/AbstractFullyQualifiedNameInstantiator.java
  transactionoutbox-jooq/src/test/java/com/gruelbox/transactionoutbox/jooq/acceptance/TestJooqThreadLocalMSSqlServer2019.java
  transactionoutbox-jooq/src/test/java/com/gruelbox/transactionoutbox/jooq/acceptance/TestJooqThreadLocalMySql5.java
  transactionoutbox-testing/src/main/java/com/gruelbox/transactionoutbox/testing/AbstractAcceptanceTest.java
Labels: Review effort 4/5
